backend:
  name: github
  repo: mathieutu/labo-courtois
  branch: main
media_folder: "public/img/"
public_folder: "/img/"
collections:
  - label: "Textes"
    name: "textes"
    files:
    - name: "textes"
      label: "Textes"
      label_singular: "Texte"
      file: "src/data.json"
      create: true
      delete: true
      fields:
        - { label: "Titre", name: "titre", widget: "string" }
        - { label: "Logo", name: "img", widget: "image", allow_multiple: false }


        - label: Miel
          name: list
          widget: list
          fields:
            - { label: "Titre", name: "titre", widget: "string" }
            - { label: "Provenance", name: "provenance", widget: "string" }
            - { label: "Prix", name: "prix", widget: "number", value_type: "float", step: 0.01 }
            - { label: "Rupture de stock", name: "rupture", widget: "boolean", default: false }
            - { label: "Description", name: "description", widget: "text" }
            - { label: 'Couleur', name: 'color', widget: 'color', allowInput: true }
            - { label: "Quantité", name: "quantite", widget: "string", default: "500g"}
            - { label: "Image", name: "img", widget: "image", allow_multiple: false }
            - { label: "Masquer", name: "hide", widget: "boolean", default: false }
